// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: math_operations.proto
// Protobuf C++ Version: 5.28.3

#include "math_operations.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace math {

inline constexpr Parm2Result::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : error_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        z_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Parm2Result::Parm2Result(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Parm2ResultDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Parm2ResultDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Parm2ResultDefaultTypeInternal() {}
  union {
    Parm2Result _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Parm2ResultDefaultTypeInternal _Parm2Result_default_instance_;

inline constexpr Parm2Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : x_{0},
        y_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Parm2Request::Parm2Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Parm2RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Parm2RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Parm2RequestDefaultTypeInternal() {}
  union {
    Parm2Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Parm2RequestDefaultTypeInternal _Parm2Request_default_instance_;
}  // namespace math
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_math_5foperations_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_math_5foperations_2eproto = nullptr;
const ::uint32_t
    TableStruct_math_5foperations_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::math::Parm2Request, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::math::Parm2Request, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::math::Parm2Request, _impl_.y_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::math::Parm2Result, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::math::Parm2Result, _impl_.z_),
        PROTOBUF_FIELD_OFFSET(::math::Parm2Result, _impl_.error_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::math::Parm2Request)},
        {10, -1, -1, sizeof(::math::Parm2Result)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::math::_Parm2Request_default_instance_._instance,
    &::math::_Parm2Result_default_instance_._instance,
};
const char descriptor_table_protodef_math_5foperations_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025math_operations.proto\022\004math\"$\n\014Parm2Re"
    "quest\022\t\n\001x\030\001 \001(\001\022\t\n\001y\030\002 \001(\001\"\'\n\013Parm2Resu"
    "lt\022\t\n\001z\030\001 \001(\001\022\r\n\005error\030\002 \001(\t2\363\001\n\013MathSer"
    "vice\022,\n\003Add\022\022.math.Parm2Request\032\021.math.P"
    "arm2Result\022,\n\003Sub\022\022.math.Parm2Request\032\021."
    "math.Parm2Result\022,\n\003Mul\022\022.math.Parm2Requ"
    "est\032\021.math.Parm2Result\022,\n\003Div\022\022.math.Par"
    "m2Request\032\021.math.Parm2Result\022,\n\003Pow\022\022.ma"
    "th.Parm2Request\032\021.math.Parm2Resultb\006prot"
    "o3"
};
static ::absl::once_flag descriptor_table_math_5foperations_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_math_5foperations_2eproto = {
    false,
    false,
    362,
    descriptor_table_protodef_math_5foperations_2eproto,
    "math_operations.proto",
    &descriptor_table_math_5foperations_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_default_instances,
    TableStruct_math_5foperations_2eproto::offsets,
    file_level_enum_descriptors_math_5foperations_2eproto,
    file_level_service_descriptors_math_5foperations_2eproto,
};
namespace math {
// ===================================================================

class Parm2Request::_Internal {
 public:
};

Parm2Request::Parm2Request(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:math.Parm2Request)
}
Parm2Request::Parm2Request(
    ::google::protobuf::Arena* arena, const Parm2Request& from)
    : Parm2Request(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE Parm2Request::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Parm2Request::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, x_),
           0,
           offsetof(Impl_, y_) -
               offsetof(Impl_, x_) +
               sizeof(Impl_::y_));
}
Parm2Request::~Parm2Request() {
  // @@protoc_insertion_point(destructor:math.Parm2Request)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Parm2Request::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Parm2Request::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Parm2Request_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Parm2Request::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Parm2Request>(),
            ::google::protobuf::Message::GetNewImpl<Parm2Request>(),
            ::google::protobuf::Message::GetClearImpl<Parm2Request>(), &Parm2Request::ByteSizeLong,
                &Parm2Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Parm2Request, _impl_._cached_size_),
            false,
        },
        &Parm2Request::kDescriptorMethods,
        &descriptor_table_math_5foperations_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Parm2Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> Parm2Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::math::Parm2Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double y = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(Parm2Request, _impl_.y_)}},
    // double x = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(Parm2Request, _impl_.x_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double x = 1;
    {PROTOBUF_FIELD_OFFSET(Parm2Request, _impl_.x_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double y = 2;
    {PROTOBUF_FIELD_OFFSET(Parm2Request, _impl_.y_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Parm2Request::Clear() {
// @@protoc_insertion_point(message_clear_start:math.Parm2Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.x_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.y_) -
      reinterpret_cast<char*>(&_impl_.x_)) + sizeof(_impl_.y_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Parm2Request::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Parm2Request& this_ = static_cast<const Parm2Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Parm2Request::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Parm2Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:math.Parm2Request)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double x = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_x(), target);
          }

          // double y = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_y(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:math.Parm2Request)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Parm2Request::ByteSizeLong(const MessageLite& base) {
          const Parm2Request& this_ = static_cast<const Parm2Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Parm2Request::ByteSizeLong() const {
          const Parm2Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:math.Parm2Request)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double x = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_x()) != 0) {
              total_size += 9;
            }
            // double y = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_y()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Parm2Request::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Parm2Request*>(&to_msg);
  auto& from = static_cast<const Parm2Request&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:math.Parm2Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_x()) != 0) {
    _this->_impl_.x_ = from._impl_.x_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_y()) != 0) {
    _this->_impl_.y_ = from._impl_.y_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Parm2Request::CopyFrom(const Parm2Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:math.Parm2Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Parm2Request::InternalSwap(Parm2Request* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Parm2Request, _impl_.y_)
      + sizeof(Parm2Request::_impl_.y_)
      - PROTOBUF_FIELD_OFFSET(Parm2Request, _impl_.x_)>(
          reinterpret_cast<char*>(&_impl_.x_),
          reinterpret_cast<char*>(&other->_impl_.x_));
}

::google::protobuf::Metadata Parm2Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Parm2Result::_Internal {
 public:
};

Parm2Result::Parm2Result(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:math.Parm2Result)
}
inline PROTOBUF_NDEBUG_INLINE Parm2Result::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::math::Parm2Result& from_msg)
      : error_(arena, from.error_),
        _cached_size_{0} {}

Parm2Result::Parm2Result(
    ::google::protobuf::Arena* arena,
    const Parm2Result& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Parm2Result* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.z_ = from._impl_.z_;

  // @@protoc_insertion_point(copy_constructor:math.Parm2Result)
}
inline PROTOBUF_NDEBUG_INLINE Parm2Result::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : error_(arena),
        _cached_size_{0} {}

inline void Parm2Result::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.z_ = {};
}
Parm2Result::~Parm2Result() {
  // @@protoc_insertion_point(destructor:math.Parm2Result)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Parm2Result::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.error_.Destroy();
  _impl_.~Impl_();
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::MessageLite::ClassDataFull
    Parm2Result::_class_data_ = {
        ::google::protobuf::Message::ClassData{
            &_Parm2Result_default_instance_._instance,
            &_table_.header,
            nullptr,  // OnDemandRegisterArenaDtor
            nullptr,  // IsInitialized
            &Parm2Result::MergeImpl,
#if defined(PROTOBUF_CUSTOM_VTABLE)
            ::google::protobuf::Message::GetDeleteImpl<Parm2Result>(),
            ::google::protobuf::Message::GetNewImpl<Parm2Result>(),
            ::google::protobuf::Message::GetClearImpl<Parm2Result>(), &Parm2Result::ByteSizeLong,
                &Parm2Result::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(Parm2Result, _impl_._cached_size_),
            false,
        },
        &Parm2Result::kDescriptorMethods,
        &descriptor_table_math_5foperations_2eproto,
        nullptr,  // tracker
};
const ::google::protobuf::MessageLite::ClassData* Parm2Result::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 30, 2> Parm2Result::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::math::Parm2Result>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string error = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Parm2Result, _impl_.error_)}},
    // double z = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(Parm2Result, _impl_.z_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double z = 1;
    {PROTOBUF_FIELD_OFFSET(Parm2Result, _impl_.z_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // string error = 2;
    {PROTOBUF_FIELD_OFFSET(Parm2Result, _impl_.error_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\20\0\5\0\0\0\0\0"
    "math.Parm2Result"
    "error"
  }},
};

PROTOBUF_NOINLINE void Parm2Result::Clear() {
// @@protoc_insertion_point(message_clear_start:math.Parm2Result)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.error_.ClearToEmpty();
  _impl_.z_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Parm2Result::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Parm2Result& this_ = static_cast<const Parm2Result&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Parm2Result::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Parm2Result& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:math.Parm2Result)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double z = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_z()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_z(), target);
          }

          // string error = 2;
          if (!this_._internal_error().empty()) {
            const std::string& _s = this_._internal_error();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "math.Parm2Result.error");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:math.Parm2Result)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Parm2Result::ByteSizeLong(const MessageLite& base) {
          const Parm2Result& this_ = static_cast<const Parm2Result&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Parm2Result::ByteSizeLong() const {
          const Parm2Result& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:math.Parm2Result)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string error = 2;
            if (!this_._internal_error().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_error());
            }
            // double z = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_z()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Parm2Result::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Parm2Result*>(&to_msg);
  auto& from = static_cast<const Parm2Result&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:math.Parm2Result)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_error().empty()) {
    _this->_internal_set_error(from._internal_error());
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_z()) != 0) {
    _this->_impl_.z_ = from._impl_.z_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Parm2Result::CopyFrom(const Parm2Result& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:math.Parm2Result)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Parm2Result::InternalSwap(Parm2Result* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.error_, &other->_impl_.error_, arena);
        swap(_impl_.z_, other->_impl_.z_);
}

::google::protobuf::Metadata Parm2Result::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace math
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_math_5foperations_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
