// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: math_operations.proto
#ifndef GRPC_math_5foperations_2eproto__INCLUDED
#define GRPC_math_5foperations_2eproto__INCLUDED

#include "math_operations.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace math {

class MathService final {
 public:
  static constexpr char const* service_full_name() {
    return "math.MathService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Add(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> AsyncAdd(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> PrepareAsyncAdd(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(PrepareAsyncAddRaw(context, request, cq));
    }
    virtual ::grpc::Status Sub(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> AsyncSub(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(AsyncSubRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> PrepareAsyncSub(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(PrepareAsyncSubRaw(context, request, cq));
    }
    virtual ::grpc::Status Mul(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> AsyncMul(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(AsyncMulRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> PrepareAsyncMul(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(PrepareAsyncMulRaw(context, request, cq));
    }
    virtual ::grpc::Status Div(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> AsyncDiv(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(AsyncDivRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> PrepareAsyncDiv(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(PrepareAsyncDivRaw(context, request, cq));
    }
    virtual ::grpc::Status Pow(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> AsyncPow(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(AsyncPowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>> PrepareAsyncPow(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>>(PrepareAsyncPowRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Add(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Add(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Sub(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Sub(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Mul(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Mul(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Div(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Div(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Pow(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Pow(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* AsyncAddRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* AsyncSubRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* PrepareAsyncSubRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* AsyncMulRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* PrepareAsyncMulRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* AsyncDivRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* PrepareAsyncDivRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* AsyncPowRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::Parm2Result>* PrepareAsyncPowRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Add(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> AsyncAdd(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> PrepareAsyncAdd(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(PrepareAsyncAddRaw(context, request, cq));
    }
    ::grpc::Status Sub(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> AsyncSub(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(AsyncSubRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> PrepareAsyncSub(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(PrepareAsyncSubRaw(context, request, cq));
    }
    ::grpc::Status Mul(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> AsyncMul(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(AsyncMulRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> PrepareAsyncMul(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(PrepareAsyncMulRaw(context, request, cq));
    }
    ::grpc::Status Div(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> AsyncDiv(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(AsyncDivRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> PrepareAsyncDiv(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(PrepareAsyncDivRaw(context, request, cq));
    }
    ::grpc::Status Pow(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::math::Parm2Result* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> AsyncPow(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(AsyncPowRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>> PrepareAsyncPow(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>>(PrepareAsyncPowRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Add(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) override;
      void Add(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Sub(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) override;
      void Sub(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Mul(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) override;
      void Mul(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Div(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) override;
      void Div(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Pow(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, std::function<void(::grpc::Status)>) override;
      void Pow(::grpc::ClientContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* AsyncAddRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* AsyncSubRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* PrepareAsyncSubRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* AsyncMulRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* PrepareAsyncMulRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* AsyncDivRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* PrepareAsyncDivRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* AsyncPowRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::Parm2Result>* PrepareAsyncPowRaw(::grpc::ClientContext* context, const ::math::Parm2Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Add_;
    const ::grpc::internal::RpcMethod rpcmethod_Sub_;
    const ::grpc::internal::RpcMethod rpcmethod_Mul_;
    const ::grpc::internal::RpcMethod rpcmethod_Div_;
    const ::grpc::internal::RpcMethod rpcmethod_Pow_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Add(::grpc::ServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response);
    virtual ::grpc::Status Sub(::grpc::ServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response);
    virtual ::grpc::Status Mul(::grpc::ServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response);
    virtual ::grpc::Status Div(::grpc::ServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response);
    virtual ::grpc::Status Pow(::grpc::ServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Add() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd(::grpc::ServerContext* context, ::math::Parm2Request* request, ::grpc::ServerAsyncResponseWriter< ::math::Parm2Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Sub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Sub() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Sub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sub(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSub(::grpc::ServerContext* context, ::math::Parm2Request* request, ::grpc::ServerAsyncResponseWriter< ::math::Parm2Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Mul : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Mul() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Mul() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mul(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMul(::grpc::ServerContext* context, ::math::Parm2Request* request, ::grpc::ServerAsyncResponseWriter< ::math::Parm2Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Div : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Div() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Div() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Div(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDiv(::grpc::ServerContext* context, ::math::Parm2Request* request, ::grpc::ServerAsyncResponseWriter< ::math::Parm2Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Pow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Pow() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Pow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pow(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPow(::grpc::ServerContext* context, ::math::Parm2Request* request, ::grpc::ServerAsyncResponseWriter< ::math::Parm2Result>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Add<WithAsyncMethod_Sub<WithAsyncMethod_Mul<WithAsyncMethod_Div<WithAsyncMethod_Pow<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Add() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response) { return this->Add(context, request, response); }));}
    void SetMessageAllocatorFor_Add(
        ::grpc::MessageAllocator< ::math::Parm2Request, ::math::Parm2Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Add(
      ::grpc::CallbackServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Sub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Sub() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response) { return this->Sub(context, request, response); }));}
    void SetMessageAllocatorFor_Sub(
        ::grpc::MessageAllocator< ::math::Parm2Request, ::math::Parm2Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Sub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sub(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sub(
      ::grpc::CallbackServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Mul : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Mul() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response) { return this->Mul(context, request, response); }));}
    void SetMessageAllocatorFor_Mul(
        ::grpc::MessageAllocator< ::math::Parm2Request, ::math::Parm2Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Mul() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mul(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Mul(
      ::grpc::CallbackServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Div : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Div() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response) { return this->Div(context, request, response); }));}
    void SetMessageAllocatorFor_Div(
        ::grpc::MessageAllocator< ::math::Parm2Request, ::math::Parm2Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Div() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Div(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Div(
      ::grpc::CallbackServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Pow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Pow() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::Parm2Request* request, ::math::Parm2Result* response) { return this->Pow(context, request, response); }));}
    void SetMessageAllocatorFor_Pow(
        ::grpc::MessageAllocator< ::math::Parm2Request, ::math::Parm2Result>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::Parm2Request, ::math::Parm2Result>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Pow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pow(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Pow(
      ::grpc::CallbackServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Add<WithCallbackMethod_Sub<WithCallbackMethod_Mul<WithCallbackMethod_Div<WithCallbackMethod_Pow<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Add() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Sub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Sub() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Sub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sub(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Mul : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Mul() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Mul() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mul(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Div : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Div() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Div() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Div(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Pow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Pow() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Pow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pow(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Add() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Sub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Sub() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Sub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sub(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSub(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Mul : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Mul() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Mul() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mul(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMul(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Div : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Div() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Div() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Div(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDiv(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Pow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Pow() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Pow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pow(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPow(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Add() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Add(context, request, response); }));
    }
    ~WithRawCallbackMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Add(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Sub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Sub() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Sub(context, request, response); }));
    }
    ~WithRawCallbackMethod_Sub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Sub(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Sub(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Mul : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Mul() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Mul(context, request, response); }));
    }
    ~WithRawCallbackMethod_Mul() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Mul(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Mul(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Div : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Div() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Div(context, request, response); }));
    }
    ~WithRawCallbackMethod_Div() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Div(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Div(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Pow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Pow() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Pow(context, request, response); }));
    }
    ~WithRawCallbackMethod_Pow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Pow(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Pow(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Add() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::Parm2Request, ::math::Parm2Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::Parm2Request, ::math::Parm2Result>* streamer) {
                       return this->StreamedAdd(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAdd(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::Parm2Request,::math::Parm2Result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Sub : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Sub() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::Parm2Request, ::math::Parm2Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::Parm2Request, ::math::Parm2Result>* streamer) {
                       return this->StreamedSub(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Sub() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Sub(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSub(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::Parm2Request,::math::Parm2Result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Mul : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Mul() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::Parm2Request, ::math::Parm2Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::Parm2Request, ::math::Parm2Result>* streamer) {
                       return this->StreamedMul(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Mul() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Mul(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMul(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::Parm2Request,::math::Parm2Result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Div : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Div() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::Parm2Request, ::math::Parm2Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::Parm2Request, ::math::Parm2Result>* streamer) {
                       return this->StreamedDiv(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Div() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Div(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDiv(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::Parm2Request,::math::Parm2Result>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Pow : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Pow() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::Parm2Request, ::math::Parm2Result>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::Parm2Request, ::math::Parm2Result>* streamer) {
                       return this->StreamedPow(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Pow() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Pow(::grpc::ServerContext* /*context*/, const ::math::Parm2Request* /*request*/, ::math::Parm2Result* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPow(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::Parm2Request,::math::Parm2Result>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Add<WithStreamedUnaryMethod_Sub<WithStreamedUnaryMethod_Mul<WithStreamedUnaryMethod_Div<WithStreamedUnaryMethod_Pow<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Add<WithStreamedUnaryMethod_Sub<WithStreamedUnaryMethod_Mul<WithStreamedUnaryMethod_Div<WithStreamedUnaryMethod_Pow<Service > > > > > StreamedService;
};

}  // namespace math


#endif  // GRPC_math_5foperations_2eproto__INCLUDED
