// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: math_operations.proto
#ifndef GRPC_math_5foperations_2eproto__INCLUDED
#define GRPC_math_5foperations_2eproto__INCLUDED

#include "math_operations.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace math {

class MathService final {
 public:
  static constexpr char const* service_full_name() {
    return "math.MathService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Add(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> AsyncAdd(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> PrepareAsyncAdd(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(PrepareAsyncAddRaw(context, request, cq));
    }
    virtual ::grpc::Status Subtract(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> AsyncSubtract(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(AsyncSubtractRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> PrepareAsyncSubtract(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(PrepareAsyncSubtractRaw(context, request, cq));
    }
    virtual ::grpc::Status Multiply(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> AsyncMultiply(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(AsyncMultiplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> PrepareAsyncMultiply(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(PrepareAsyncMultiplyRaw(context, request, cq));
    }
    virtual ::grpc::Status Divide(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> AsyncDivide(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(AsyncDivideRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> PrepareAsyncDivide(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(PrepareAsyncDivideRaw(context, request, cq));
    }
    virtual ::grpc::Status Power(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> AsyncPower(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(AsyncPowerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>> PrepareAsyncPower(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>>(PrepareAsyncPowerRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Add(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Add(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Subtract(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Subtract(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Multiply(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Multiply(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Divide(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Divide(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Power(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Power(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* AsyncAddRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* AsyncSubtractRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* PrepareAsyncSubtractRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* AsyncMultiplyRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* PrepareAsyncMultiplyRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* AsyncDivideRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* PrepareAsyncDivideRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* AsyncPowerRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::math::MathResponse>* PrepareAsyncPowerRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Add(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> AsyncAdd(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(AsyncAddRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> PrepareAsyncAdd(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(PrepareAsyncAddRaw(context, request, cq));
    }
    ::grpc::Status Subtract(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> AsyncSubtract(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(AsyncSubtractRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> PrepareAsyncSubtract(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(PrepareAsyncSubtractRaw(context, request, cq));
    }
    ::grpc::Status Multiply(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> AsyncMultiply(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(AsyncMultiplyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> PrepareAsyncMultiply(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(PrepareAsyncMultiplyRaw(context, request, cq));
    }
    ::grpc::Status Divide(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> AsyncDivide(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(AsyncDivideRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> PrepareAsyncDivide(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(PrepareAsyncDivideRaw(context, request, cq));
    }
    ::grpc::Status Power(::grpc::ClientContext* context, const ::math::MathRequest& request, ::math::MathResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> AsyncPower(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(AsyncPowerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>> PrepareAsyncPower(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::math::MathResponse>>(PrepareAsyncPowerRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Add(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) override;
      void Add(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Subtract(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) override;
      void Subtract(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Multiply(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) override;
      void Multiply(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Divide(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) override;
      void Divide(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Power(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, std::function<void(::grpc::Status)>) override;
      void Power(::grpc::ClientContext* context, const ::math::MathRequest* request, ::math::MathResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* AsyncAddRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* AsyncSubtractRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* PrepareAsyncSubtractRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* AsyncMultiplyRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* PrepareAsyncMultiplyRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* AsyncDivideRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* PrepareAsyncDivideRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* AsyncPowerRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::math::MathResponse>* PrepareAsyncPowerRaw(::grpc::ClientContext* context, const ::math::MathRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Add_;
    const ::grpc::internal::RpcMethod rpcmethod_Subtract_;
    const ::grpc::internal::RpcMethod rpcmethod_Multiply_;
    const ::grpc::internal::RpcMethod rpcmethod_Divide_;
    const ::grpc::internal::RpcMethod rpcmethod_Power_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Add(::grpc::ServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response);
    virtual ::grpc::Status Subtract(::grpc::ServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response);
    virtual ::grpc::Status Multiply(::grpc::ServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response);
    virtual ::grpc::Status Divide(::grpc::ServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response);
    virtual ::grpc::Status Power(::grpc::ServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Add() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd(::grpc::ServerContext* context, ::math::MathRequest* request, ::grpc::ServerAsyncResponseWriter< ::math::MathResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Subtract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Subtract() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Subtract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subtract(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubtract(::grpc::ServerContext* context, ::math::MathRequest* request, ::grpc::ServerAsyncResponseWriter< ::math::MathResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Multiply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Multiply() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_Multiply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Multiply(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMultiply(::grpc::ServerContext* context, ::math::MathRequest* request, ::grpc::ServerAsyncResponseWriter< ::math::MathResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Divide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Divide() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Divide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Divide(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDivide(::grpc::ServerContext* context, ::math::MathRequest* request, ::grpc::ServerAsyncResponseWriter< ::math::MathResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Power : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Power() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_Power() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Power(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPower(::grpc::ServerContext* context, ::math::MathRequest* request, ::grpc::ServerAsyncResponseWriter< ::math::MathResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Add<WithAsyncMethod_Subtract<WithAsyncMethod_Multiply<WithAsyncMethod_Divide<WithAsyncMethod_Power<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Add() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response) { return this->Add(context, request, response); }));}
    void SetMessageAllocatorFor_Add(
        ::grpc::MessageAllocator< ::math::MathRequest, ::math::MathResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Add(
      ::grpc::CallbackServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Subtract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Subtract() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response) { return this->Subtract(context, request, response); }));}
    void SetMessageAllocatorFor_Subtract(
        ::grpc::MessageAllocator< ::math::MathRequest, ::math::MathResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Subtract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subtract(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Subtract(
      ::grpc::CallbackServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Multiply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Multiply() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response) { return this->Multiply(context, request, response); }));}
    void SetMessageAllocatorFor_Multiply(
        ::grpc::MessageAllocator< ::math::MathRequest, ::math::MathResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Multiply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Multiply(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Multiply(
      ::grpc::CallbackServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Divide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Divide() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response) { return this->Divide(context, request, response); }));}
    void SetMessageAllocatorFor_Divide(
        ::grpc::MessageAllocator< ::math::MathRequest, ::math::MathResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Divide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Divide(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Divide(
      ::grpc::CallbackServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Power : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Power() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::math::MathRequest* request, ::math::MathResponse* response) { return this->Power(context, request, response); }));}
    void SetMessageAllocatorFor_Power(
        ::grpc::MessageAllocator< ::math::MathRequest, ::math::MathResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::math::MathRequest, ::math::MathResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Power() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Power(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Power(
      ::grpc::CallbackServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Add<WithCallbackMethod_Subtract<WithCallbackMethod_Multiply<WithCallbackMethod_Divide<WithCallbackMethod_Power<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Add() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Subtract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Subtract() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Subtract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subtract(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Multiply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Multiply() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_Multiply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Multiply(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Divide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Divide() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Divide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Divide(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Power : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Power() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_Power() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Power(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Add() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAdd(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Subtract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Subtract() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Subtract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subtract(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSubtract(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Multiply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Multiply() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_Multiply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Multiply(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMultiply(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Divide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Divide() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Divide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Divide(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDivide(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Power : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Power() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_Power() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Power(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestPower(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Add() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Add(context, request, response); }));
    }
    ~WithRawCallbackMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Add(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Subtract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Subtract() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Subtract(context, request, response); }));
    }
    ~WithRawCallbackMethod_Subtract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Subtract(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Subtract(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Multiply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Multiply() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Multiply(context, request, response); }));
    }
    ~WithRawCallbackMethod_Multiply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Multiply(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Multiply(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Divide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Divide() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Divide(context, request, response); }));
    }
    ~WithRawCallbackMethod_Divide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Divide(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Divide(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Power : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Power() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Power(context, request, response); }));
    }
    ~WithRawCallbackMethod_Power() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Power(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Power(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Add : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Add() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::MathRequest, ::math::MathResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::MathRequest, ::math::MathResponse>* streamer) {
                       return this->StreamedAdd(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Add() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Add(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAdd(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::MathRequest,::math::MathResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Subtract : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Subtract() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::MathRequest, ::math::MathResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::MathRequest, ::math::MathResponse>* streamer) {
                       return this->StreamedSubtract(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Subtract() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Subtract(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSubtract(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::MathRequest,::math::MathResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Multiply : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Multiply() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::MathRequest, ::math::MathResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::MathRequest, ::math::MathResponse>* streamer) {
                       return this->StreamedMultiply(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Multiply() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Multiply(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMultiply(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::MathRequest,::math::MathResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Divide : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Divide() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::MathRequest, ::math::MathResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::MathRequest, ::math::MathResponse>* streamer) {
                       return this->StreamedDivide(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Divide() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Divide(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDivide(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::MathRequest,::math::MathResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Power : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Power() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::math::MathRequest, ::math::MathResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::math::MathRequest, ::math::MathResponse>* streamer) {
                       return this->StreamedPower(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Power() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Power(::grpc::ServerContext* /*context*/, const ::math::MathRequest* /*request*/, ::math::MathResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedPower(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::math::MathRequest,::math::MathResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Add<WithStreamedUnaryMethod_Subtract<WithStreamedUnaryMethod_Multiply<WithStreamedUnaryMethod_Divide<WithStreamedUnaryMethod_Power<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Add<WithStreamedUnaryMethod_Subtract<WithStreamedUnaryMethod_Multiply<WithStreamedUnaryMethod_Divide<WithStreamedUnaryMethod_Power<Service > > > > > StreamedService;
};

}  // namespace math


#endif  // GRPC_math_5foperations_2eproto__INCLUDED
